[package]
name = "http-range-test"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.4"
futures = "0.3.15"
clap = "3.0.0-beta.2"
